global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'springboot-app'
    metrics_path: '/foyer/actuator/prometheus'
    static_configs:
      - targets: ['springboot:8089']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['172.18.0.3:8080']